window.BANCO_PREGUNTAS = [
  // =======================
// MÓDULO 1 — Información como activo (CIA / Clasificación / Inventario / Metadatos / Backups / Cifrado / Ley)
// =======================
{ id:'m1_q101', modulo:1, pregunta:'¿Cuál pilar protege contra ALTERACIONES no autorizadas de la información?',
  opciones:['Disponibilidad','Integridad','Confidencialidad'], correcta:1,
  explica:'Integridad = que los datos no se modifiquen indebidamente.' },
{ id:'m1_q102', modulo:1, pregunta:'Un padrón con DNI de estudiantes y notas finales se clasifica como…',
  opciones:['Uso interno','Pública','Confidencial'], correcta:2,
  explica:'Contiene datos personales/sensibles → confidencial.' },
{ id:'m1_q103', modulo:1, pregunta:'¿Qué conviene hacer ANTES de definir controles sobre un repositorio?',
  opciones:['Elegir un algoritmo de cifrado','Inventariar y clasificar la información','Comprar más almacenamiento'], correcta:1,
  explica:'Inventario + clasificación guían los controles adecuados.' },
{ id:'m1_q104', modulo:1, pregunta:'Publicar documentos PDF en la web institucional sin revisar metadatos puede…',
  opciones:['Mejorar el SEO','Exponer autor/fecha/ruta interna','Reducir tamaño del archivo'], correcta:1,
  explica:'Metadatos pueden filtrar info de contexto no deseada.' },
{ id:'m1_q105', modulo:1, pregunta:'¿Qué opción refleja la regla 3–2–1 de copias de seguridad?',
  opciones:['3 copias, 2 soportes distintos, 1 fuera del sitio','3 copias en la misma PC','2 copias en 2 nubes'], correcta:0,
  explica:'3-2-1: tres copias, dos soportes, una off-site.' },
{ id:'m1_q106', modulo:1, pregunta:'Para archivos sensibles en nube, ¿qué práctica es correcta?',
  opciones:['Compartir por enlace público','Cifrarlos y limitar acceso por rol','Dejar sin permisos para ahorrar tiempo'], correcta:1,
  explica:'Cifrado + permisos mínimos reducen exposición.' },
{ id:'m1_q107', modulo:1, pregunta:'Ransomware afecta principalmente el pilar de…',
  opciones:['Disponibilidad','Integridad','Confidencialidad'], correcta:0,
  explica:'Bloquea el acceso (disponibilidad) y puede afectar otros pilares.' },
{ id:'m1_q108', modulo:1, pregunta:'¿Cuál es un buen ejemplo de etiquetado?',
  opciones:['Acta1.docx','[confidencial]Acta_final_2025.docx','final.doc'], correcta:1,
  explica:'Etiquetar ayuda a tratar la info según su clasificación.' },
{ id:'m1_q109', modulo:1, pregunta:'Para cifrar archivos sensibles, una práctica adecuada es…',
  opciones:['Usar algoritmos fuertes (p.ej., AES-256)','Guardar claves en un correo propio','Compartir la clave por chat sin contexto'], correcta:0,
  explica:'Algoritmos robustos + custodia segura de claves.' },
{ id:'m1_q110', modulo:1, pregunta:'Respecto a la Ley 25.326 (AR) y Habeas Data:',
  opciones:['No reconoce derechos del titular','Exige consentimiento informado y seguridad','Solo aplica a empresas privadas'], correcta:1,
  explica:'Reconoce derechos y exige resguardo y finalidad informada.' },

// =======================
// MÓDULO 2 — Correo electrónico (phishing / adjuntos / enlaces / privacidad)
// =======================
{ id:'m2_q101', modulo:2, pregunta:'El texto visible del link dice “UNCUYO”, pero el dominio real NO es uncuyo.edu.ar. Lo correcto es…',
  opciones:['Hacer clic igual','Reportar y entrar solo por el sitio oficial','Responder pidiendo más info'], correcta:1,
  explica:'Importa el dominio real; verificá por canal oficial.' },
{ id:'m2_q102', modulo:2, pregunta:'¿Qué archivo es más riesgoso en un correo no esperado?',
  opciones:['.pdf simple','.docm con macros','.txt'], correcta:1,
  explica:'Los .docm/.xlsm con macros son vectores frecuentes de malware.' },
{ id:'m2_q103', modulo:2, pregunta:'Para envíos masivos y proteger direcciones de terceros usá…',
  opciones:['CC','CCO','Responder a todos'], correcta:1,
  explica:'CCO oculta las direcciones entre destinatarios.' },
{ id:'m2_q104', modulo:2, pregunta:'Descarga automática de imágenes en el correo:',
  opciones:['Conviene activarla siempre','Puede usarse para rastreo; mejor desactivarla','No tiene impacto en seguridad'], correcta:1,
  explica:'Evitá la carga automática para no filtrar apertura/ubicación.' },
{ id:'m2_q105', modulo:2, pregunta:'Señal típica de phishing:',
  opciones:['Remitente personalizado y coherente','Tono urgente/amenazante y errores de redacción','Firma completa y datos verificados'], correcta:1,
  explica:'Urgencia + errores/impersonalidad = bandera roja.' },
{ id:'m2_q106', modulo:2, pregunta:'Hiciste clic en un enlace dudoso. ¿Primer paso?',
  opciones:['Ignorar si no pasó nada','Cambiar contraseñas relacionadas y avisar a TI','Compartir el link con colegas'], correcta:1,
  explica:'Mitigá impacto y reportá para contención temprana.' },
{ id:'m2_q107', modulo:2, pregunta:'¿Cuál es una buena práctica con adjuntos inesperados?',
  opciones:['Abrirlos en el celular “que es más seguro”','Validar por canal oficial y escanear antes','Descomprimir y ver qué hay'], correcta:1,
  explica:'Validá remitente y analizá con antivirus/servicios multi-motor.' },
{ id:'m2_q108', modulo:2, pregunta:'El remitente parece real pero sospechás spoofing. ¿Qué ayuda?',
  opciones:['Mirar solo el nombre para mostrar','Revisar cabeceras o consultar a TI','Responder para confirmar'], correcta:1,
  explica:'Cabeceras y análisis técnico confirman su origen.' },
{ id:'m2_q109', modulo:2, pregunta:'Si dudás de la veracidad de un correo “de tu banco”:',
  opciones:['Respondé desde ese correo','Buscá el teléfono oficial y llamá','Clic al link para “ver si abre”'], correcta:1,
  explica:'Verificá por canal independiente (sitio/teléfono oficial).' },
{ id:'m2_q110', modulo:2, pregunta:'Mensajes con acortadores tipo bit.ly:',
  opciones:['Siempre son confiables','Ocultan el dominio; tratarlos con cautela','Solo se usan en campañas oficiales'], correcta:1,
  explica:'El acortado es opaco; verificá destino antes de abrir.' },

// =======================
// MÓDULO 3 — Contraseñas + MFA + Gestores
// =======================
{ id:'m3_q101', modulo:3, pregunta:'La contraseña “Sol#Lluvia_Arco 27” es robusta sobre todo por…',
  opciones:['Usar solo símbolos','Longitud + mezcla + frase', 'No tener números'], correcta:1,
  explica:'Frase larga con diversidad de caracteres = alta entropía.' },
{ id:'m3_q102', modulo:3, pregunta:'¿Qué NO corresponde con un buen uso de gestor de contraseñas?',
  opciones:['Generar claves aleatorias por sitio','Compartir la maestra por chat con un colega','Autocompletar solo en sitios confiables'], correcta:1,
  explica:'La maestra jamás se comparte; es la llave del cofre.' },
{ id:'m3_q103', modulo:3, pregunta:'Sobre cambios de contraseña:',
  opciones:['Cambiar forzado cada semana siempre','Cambiar al detectar filtración o riesgo','Nunca cambiar'], correcta:1,
  explica:'Cambios por incidente/indicio; no rotaciones absurdamente cortas.' },
{ id:'m3_q104', modulo:3, pregunta:'¿Qué segundo factor ofrece mejor resistencia?',
  opciones:['SMS','TOTP/llave FIDO2/U2F','Correo electrónico'], correcta:1,
  explica:'TOTP/llaves físicas son más robustos que SMS/email.' },
{ id:'m3_q105', modulo:3, pregunta:'Buena custodia de códigos de recuperación (MFA):',
  opciones:['Guardarlos en notas del celular','Imprimir/guardar cifrados en lugar seguro','Enviarlos por mail a uno mismo'], correcta:1,
  explica:'Tratalos como secretos críticos, fuera de canales inseguros.' },
{ id:'m3_q106', modulo:3, pregunta:'Reutilizar contraseñas en varios sitios implica que…',
  opciones:['Mejorás recordación sin riesgo','Una filtración expone varias cuentas','El MFA deja de ser necesario'], correcta:1,
  explica:'La reutilización encadena compromisos entre servicios.' },
{ id:'m3_q107', modulo:3, pregunta:'Si sospechás que tu correo fue comprometido:',
  opciones:['Esperar a ver si cambia','Cambiar clave, activar MFA y cerrar sesiones','Avisar en redes sociales'], correcta:1,
  explica:'Actuá de inmediato y revocá sesiones/dispositivos.' },
{ id:'m3_q108', modulo:3, pregunta:'¿Cuál es una buena política para la contraseña maestra?',
  opciones:['Corta pero con símbolos','Larga, única y memorizable (frase)','La misma que uso en otros sitios'], correcta:1,
  explica:'Debe ser única, muy fuerte y sólo para el gestor.' },
{ id:'m3_q109', modulo:3, pregunta:'La opción “Recordar contraseña” del navegador del móvil:',
  opciones:['Mejora seguridad siempre','Puede aumentar riesgo si el equipo se pierde/roba','Es equivalente a usar gestor'], correcta:1,
  explica:'Preferí gestor dedicado y bloqueo de dispositivo.' },
{ id:'m3_q110', modulo:3, pregunta:'Para compartir acceso sin revelar la contraseña:',
  opciones:['Enviar la clave por correo','Usar cofres/colecciones del gestor','Decirla por teléfono'], correcta:1,
  explica:'Los cofres permiten compartir sin exponer la clave en texto.' },

// =======================
// MÓDULO 4 — Puesto de trabajo (mesa limpia / bloqueo / software legítimo / AV & firewall / USB)
// =======================
{ id:'m4_q101', modulo:4, pregunta:'Atajo correcto para bloquear sesión en Windows:',
  opciones:['Ctrl+Alt+Supr y esperar','Win+L','Alt+F4'], correcta:1,
  explica:'Win+L bloquea rápido el equipo.' },
{ id:'m4_q102', modulo:4, pregunta:'Documentos con datos personales olvidados en la impresora:',
  opciones:['Dejarlos ahí','Retirarlos y avisar/entregar al responsable','Fotografiarlos por si “alguien los pide”'], correcta:1,
  explica:'Prevenís exposición de datos sensibles.' },
{ id:'m4_q103', modulo:4, pregunta:'El antivirus está “pesado”. ¿Qué hacés?',
  opciones:['Desactivarlo un rato','Mantenerlo activo y pedir revisión a Soporte','Desactivar el firewall solamente'], correcta:1,
  explica:'Nunca desactives protección; pedí optimización.' },
{ id:'m4_q104', modulo:4, pregunta:'Instalar software:',
  opciones:['Desde pop-ups o sitios de terceros','Solo desde tienda/sitio oficial o por Soporte','Desde cualquier link que te pasen'], correcta:1,
  explica:'Origen legítimo y autorizado reduce malware.' },
{ id:'m4_q105', modulo:4, pregunta:'USB desconocido encontrado:',
  opciones:['Conectarlo para ver contenido','Entregar a Soporte/Seguridad sin conectarlo','Escanearlo vos mismo en tu PC personal'], correcta:1,
  explica:'Riesgo de autorun/malware; derivá al canal oficial.' },
{ id:'m4_q106', modulo:4, pregunta:'Fin de jornada recomendado:',
  opciones:['Dejar todo abierto por mañana','Apagar/bloquear y guardar dispositivos y papeles','Solo cerrar la puerta'], correcta:1,
  explica:'Cierre ordenado + custodia física reducen riesgos.' },
{ id:'m4_q107', modulo:4, pregunta:'Uso institucional de Internet implica…',
  opciones:['Descargar software crackeado','Evitar sitios de riesgo y cumplir políticas','Instalar extensiones al azar'], correcta:1,
  explica:'Respeta políticas y evitá fuentes peligrosas.' },
{ id:'m4_q108', modulo:4, pregunta:'Pantalla con información sensible en espacio compartido:',
  opciones:['Nada, total “pasan rápido”','Usar bloqueo cuando te ausentes y ubicar el monitor estratégicamente','Quitar el protector de pantalla'], correcta:1,
  explica:'Bloqueo y disposición reducen miradas ajenas.' },
{ id:'m4_q109', modulo:4, pregunta:'¿Qué combinación protege MEJOR el equipo?',
  opciones:['Antivirus sin firewall','Firewall sin antivirus','Antivirus + firewall, ambos actualizados'], correcta:2,
  explica:'Son controles complementarios; mantenelos activos.' },
{ id:'m4_q110', modulo:4, pregunta:'Papel con credenciales ya obsoletas:',
  opciones:['Guardar para archivo','Tirarlo entero en la basura','Destruirlo (triturado) igualmente'], correcta:2,
  explica:'Los residuos pueden revisarse; destruí documentos sensibles.' },

// =======================
// MÓDULO 5 — Dispositivos móviles / BYOD / VPN / Wi-Fi / Apps
// =======================
{ id:'m5_q101', modulo:5, pregunta:'En móvil, ¿qué medida ELEVA más la seguridad de acceso?',
  opciones:['Sin bloqueo para rapidez','PIN/contraseña robusta + biometría','Solo patrón de 4 puntos'], correcta:1,
  explica:'Bloqueo fuerte + biometría acelera sin bajar seguridad.' },
{ id:'m5_q102', modulo:5, pregunta:'Sobre Wi-Fi pública al acceder a sistemas:',
  opciones:['Úsala sin problema','Solo con VPN institucional o usá datos móviles','Con HTTPS alcanza siempre'], correcta:1,
  explica:'VPN o datos; la red pública es fácilmente interceptable.' },
{ id:'m5_q103', modulo:5, pregunta:'“Recordar contraseñas” en el teléfono:',
  opciones:['Mejor usar gestor de contraseñas','Siempre activarlo','Es lo mismo que MFA'], correcta:0,
  explica:'Gestor dedicado + bloqueo del dispositivo = mejor práctica.' },
{ id:'m5_q104', modulo:5, pregunta:'Permisos de apps a revisar con más cuidado:',
  opciones:['Fondos de pantalla','Accesibilidad y lectura de SMS','Acceso a vibración'], correcta:1,
  explica:'Pueden capturar códigos 2FA o controlar el dispositivo.' },
{ id:'m5_q105', modulo:5, pregunta:'Práctica correcta en BYOD:',
  opciones:['Rootear/jailbreak para “personalizar”','Registrar el equipo y usar apps autorizadas','Prestar el teléfono a terceros'], correcta:1,
  explica:'Política BYOD: registro, apps aprobadas, nada de root/jailbreak.' },
{ id:'m5_q106', modulo:5, pregunta:'Robo/pérdida del celular con cuentas abiertas:',
  opciones:['Esperar a ver si aparece','Bloqueo/geo/borrado remoto y aviso a la institución','Solo cambiar una contraseña'], correcta:1,
  explica:'Actuá de inmediato y notificá para mitigar impacto.' },
{ id:'m5_q107', modulo:5, pregunta:'En casa, seguridad de Wi-Fi:',
  opciones:['WPA2/WPA3 y WPS desactivado','WEP por compatibilidad','Clave “12345678” porque es larga'], correcta:0,
  explica:'WPA2/3 con clave robusta y WPS OFF endurece la red.' },
{ id:'m5_q108', modulo:5, pregunta:'Actualizaciones en móviles/portátiles:',
  opciones:['Postergarlas indefinidamente','Aplicarlas con regularidad (auto-update)','Solo si hay “errores”'], correcta:1,
  explica:'Mantener SO/apps actualizados cierra vulnerabilidades.' },
{ id:'m5_q109', modulo:5, pregunta:'Cargar en lugares públicos (“carga gratuita”):',
  opciones:['Usar solo tu cable/cargador o un adaptador “solo carga”','Conectar a cualquier puerto USB','Dejarlo toda la noche en un hall'], correcta:0,
  explica:'Evitá riesgos de “juice-jacking”; preferí tu cargador o data-blocker.' },
{ id:'m5_q110', modulo:5, pregunta:'Para datos sensibles en el teléfono:',
  opciones:['Descargarlos en Descargas sin cifrar','Acceder por apps oficiales y evitar copias locales','Enviar por chat personal'], correcta:1,
  explica:'Minimizá copias locales; cifrado y apps oficiales.' },

// =======================
// MÓDULO 6 — Redes sociales (privacidad / 2FA / gobernanza / suplantación / enlaces)
// =======================
{ id:'m6_q101', modulo:6, pregunta:'Para proteger cuentas institucionales de RRSS, lo esencial es…',
  opciones:['Una clave fácil compartida','Claves únicas + 2FA y accesos nominativos','Dar acceso a cualquier app externa'], correcta:1,
  explica:'Claves fuertes y 2FA; permisos controlados por rol.' },
{ id:'m6_q102', modulo:6, pregunta:'Antes de publicar una imagen del laboratorio:',
  opciones:['Publicar y borrar luego si hay quejas','Revisar fondo/metadatos y audiencias','Pedir likes al alumnado'], correcta:1,
  explica:'Evitá exponer datos/instrumental; ajustá audiencia y metadatos.' },
{ id:'m6_q103', modulo:6, pregunta:'Un DM desde perfil desconocido trae un PDF:',
  opciones:['Abrir para “ver si es real”','Reportar y validar por canal oficial','Responder pidiendo más detalles'], correcta:1,
  explica:'Tratá adjuntos como potencialmente maliciosos.' },
{ id:'m6_q104', modulo:6, pregunta:'Para que ciertas publicaciones NO las vean colegas/estudiantes:',
  opciones:['Público','Listas/Close Friends o “Amigos excepto…”','Compartir en todas las historias'], correcta:1,
  explica:'Ajustá audiencia por post con listas o exclusiones.' },
{ id:'m6_q105', modulo:6, pregunta:'Suplantación (typosquatting) de perfil institucional:',
  opciones:['Seguir y compartir para “apoyar”','Reportar por suplantación y avisar a Comunicación','Ignorar y dejar que otros decidan'], correcta:1,
  explica:'Reportá y coordina con el equipo responsable oficial.' },
{ id:'m6_q106', modulo:6, pregunta:'Apps de terceros conectadas a tus RRSS:',
  opciones:['Revisarlas y revocar las innecesarias','Dar acceso a todas por comodidad','Nunca revisar permisos'], correcta:0,
  explica:'Menos aplicaciones = menor superficie de ataque.' },
{ id:'m6_q107', modulo:6, pregunta:'Una buena práctica de conducta en redes:',
  opciones:['Responder en caliente a críticas','Verificar fuentes y mantener tono profesional','Publicar documentos internos “por transparencia”'], correcta:1,
  explica:'Profesionalismo y verificación antes de difundir.' },
{ id:'m6_q108', modulo:6, pregunta:'Enlaces acortados en RRSS:',
  opciones:['Confiables por defecto','Ocultan el destino real; verificá antes','Más seguros que enlaces largos'], correcta:1,
  explica:'Usá verificadores o accedé desde la página oficial.' },
{ id:'m6_q109', modulo:6, pregunta:'Para alternar vida personal e institucional en redes:',
  opciones:['Usar un único perfil abierto','Separar perfiles o audiencias y políticas claras','Dar la clave a un compañero'], correcta:1,
  explica:'Separación/segmentación reduce riesgos de reputación.' },
{ id:'m6_q110', modulo:6, pregunta:'Te piden datos financieros por DM desde “sorteo oficial”:',
  opciones:['Mandar los datos “por privado”','Ignorar/reporte y verificar con la cuenta verificada','Pedir un link de pago'], correcta:1,
  explica:'Nunca brindes datos financieros por redes; validá en canales oficiales.' },


// =======================
// MÓDULO 7 — Inteligencia Artificial
// =======================
{ id:'m7_q101', modulo:7, pregunta:'La Inteligencia Artificial se define como…',
  opciones:['Un software que funciona solo como calculadora','Una rama de la informática que simula inteligencia humana','Un hardware que reemplaza computadoras'], correcta:1,
  explica:'La IA desarrolla sistemas capaces de aprendizaje, razonamiento y resolución de problemas.' },

{ id:'m7_q102', modulo:7, pregunta:'Un uso común de la IA en el ámbito laboral es…',
  opciones:['Automatización de tareas repetitivas','Eliminar todos los puestos de trabajo','Hacer tareas sin supervisión humana nunca'], correcta:0,
  explica:'La IA potencia procesos como chatbots, gestión documental y optimización de recursos.' },

{ id:'m7_q103', modulo:7, pregunta:'La IA puede mejorar el bienestar laboral mediante…',
  opciones:['Vigilancia y seguridad responsable','Reemplazo de todos los empleados','Eliminar descansos'], correcta:0,
  explica:'Con monitoreo adecuado, ayuda a detectar riesgos y mejorar seguridad en el trabajo.' },

{ id:'m7_q104', modulo:7, pregunta:'Una vulnerabilidad al usar IA en el trabajo es…',
  opciones:['Subir información confidencial sin control','Que siempre sea objetiva y neutral','Que garantice privacidad absoluta'], correcta:0,
  explica:'Subir datos sensibles a servicios de IA puede exponerlos a filtraciones o ataques.' },

{ id:'m7_q105', modulo:7, pregunta:'Un compañero sube a la IA un documento con datos de clientes. ¿Es correcto?',
  opciones:['Sí, total es solo para análisis','No, la información sensible no debe compartirse','Sí, si el archivo no tiene contraseñas'], correcta:1,
  explica:'Nunca cargues información confidencial en IA pública; puede quedar expuesta.' },

{ id:'m7_q106', modulo:7, pregunta:'El sistema de IA devuelve un resultado con sesgo. ¿Qué hacés?',
  opciones:['Lo acepto, seguro es correcto','Lo uso sin verificar','Lo reviso críticamente antes de aplicarlo'], correcta:2,
  explica:'La IA puede equivocarse o estar sesgada. Siempre verificá con criterio humano antes de decidir.' },

{ id:'m7_q107', modulo:7, pregunta:'La empresa empieza a depender totalmente de la IA para tomar decisiones clave. ¿Qué práctica es correcta?',
  opciones:['Dejar que la IA decida sola, es más rápida','Usar la IA como apoyo, pero con supervisión humana','Ignorar siempre las sugerencias de IA'], correcta:1,
  explica:'La IA debe complementar al juicio humano, no reemplazarlo completamente.' },

{ id:'m7_q108', modulo:7, pregunta:'La empresa instala IA de vigilancia que graba todo lo que hacen los empleados. ¿Es correcto?',
  opciones:['Sí, porque aumenta la seguridad','No, debe haber límites y respeto a la privacidad','Sí, mientras lo informen después'], correcta:1,
  explica:'Debe existir un equilibrio: la vigilancia no puede vulnerar la privacidad ni generar un ambiente tóxico.' },

{ id:'m7_q109', modulo:7, pregunta:'La IA genera un informe con errores de cálculo. ¿Qué corresponde hacer?',
  opciones:['Confiar igual, seguro es un detalle menor','Publicarlo rápido para ganar tiempo','Revisar y validar antes de usar'], correcta:2,
  explica:'Siempre revisá resultados de IA antes de usarlos; un error puede comprometer decisiones o reputación.' },

{ id:'m7_q110', modulo:7, pregunta:'Para reducir riesgos al usar IA en la empresa, corresponde…',
  opciones:['Definir límites, gestionar accesos y capacitar empleados','Dejar que todos usen cualquier IA sin reglas','No monitorear el uso para dar libertad total'], correcta:0,
  explica:'Políticas claras, monitoreo y capacitación aseguran un uso ético y seguro de la IA.' },


];

